"""empty message

Revision ID: cbec47ae20e3
Revises: bfa1912a2dca
Create Date: 2020-06-22 14:47:14.408403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbec47ae20e3'
down_revision = 'bfa1912a2dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'message',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=1000),
               nullable=False)
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False))
    op.alter_column('comments', 'message',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=1000),
               nullable=True)
    # ### end Alembic commands ###
